### ISSUE TITLE
OpenBoard always shows ternary screen window when system has three or more screens---even if set to single screen mode

### ISSUE THREAD

**Issue by maehne** [OpenBoard-org/OpenBoard#612]
When OpenBoard starts up on a system with three or more screens, it always shows the ternary screen window---even if in the OpenBoard menu the single screen mode is selected. One has to manually close that window using the task/window manager.

I am currently using OpenBoard version 1.6.1 on Windows 11, but already noticed it in the past on Windows 10, macOS High Sierra, and Linux (Debian Buster). This issue may be related to issue #536.

**Comment by maehne** [comment]
The issue is also present in Openboard 1.6.2.

**Comment by maehne** [comment]
OpenBoard 1.7-dev commit 47a96e1d does not show a ternary screen at all: Neither in multi screen mode nor in single screen mode. Adding the third screen in the Preferences:

![grafik](https://user-images.githubusercontent.com/1174243/173028221-8f52cdb3-2828-45e4-9893-336a4da65d08.png)

has no effect.

**Comment by letsfindaway** [comment]
I just found out that the widgets of "Previous Pages" screens are only created when OpenBoard is started and not when the configuration is changed while it is running.

Can you confirm that? What happens when you restart OpenBoard with three screens configured as you have shown above?

See also my comment on #611.

And again thanks for testing - it really helps.

**Comment by letsfindaway** [comment]
Note: I just pushed a commit to https://github.com/letsfindaway/OpenBoard/tree/improve-displaymanager which should re-initialize the previous screens on-the-fly when screen configuration is changed. If you like you could test with that branch.

**Comment by maehne** [comment]
@letsfindaway: I built commit 59809586 from branch [letsfindaway/OpenBoard/tree/improve-displaymanager](https://github.com/letsfindaway/OpenBoard/tree/improve-displaymanager). I am still not able to enable the "Previous Pages" screen. In the list of used screens in the Preferences dialogue, it makes no difference if I explicitly list the numbers of the screens or leave the field empty to use all available screens. Also relaunching OpenBoard does not help to enable the third screen in OpenBoard.

**Comment by letsfindaway** [comment]
Thanks for testing. I just found out that even a third monitor would not help me: my development computer only supports two video outputs :( so I need your help.

I just pushed a commit to the branch indicated above with a slight modification for setting the geometry of the previous page widgets. It also adds a lot of debug output which could probably help. Could you give that a try?

**Comment by maehne** [comment]
@letsfindaway: I built commit ba1dcc6 from your [improve-displaymanager](https://github.com/letsfindaway/OpenBoard/commits/improve-displaymanager) branch. I am still not able to activate the Previous pages screen by adding it in the list of used screens in Preferences. Restarting the app did not help. It also did not help to delete `~/.local/share/OpenBoard/`. I did not see any relevant debug output in the shell, from which I started `build/linux/release/product/OpenBoard`. Only the following gets written repeatedly:

```
Persisting document; path is "/home/mht1/.local/share/OpenBoard/document/OpenBoard Document 2022-06-13 14-17-41.760/metadata.rdf"
[...]
```

**Comment by letsfindaway** [comment]
> I did not see any relevant debug output in the shell, from which I started `build/linux/release/product/OpenBoard`

Can you also create a Debug build? Maybe `qDebug()` output is suppressed for release builds.
